### ISSUE TITLE
Problem when last item of an OID is 0

### ISSUE THREAD

**Issue by cmammoli** [simonkowallik/Zabbix-Addons#1]
Hi, I'm using your script to split the last 2 values of an OID to monitor an HSRP router

For ex:

1.3.6.1.4.1.9.9.106.1.2.1.1.11.3.0

Where:
1.3.6.1.4.1.9.9.106.1.2.1.1 = root of the HSRP OID
11 = index with ip address of the hsrp interfaces
3 = interface id
0 = HSRP group

I run the script this way:

/etc/zabbix/externalscripts/advsnmp.discovery  ROUTERIP "-v2c -cpublic -On -Ln" 1.3.6.1.4.1.9.9.106.1.2.1.1.11 1.1 2.1
and the output is:
{
    "data":[
        {
        "{#ADVSNMPINDEX1}": "3",
        "{#ADVSNMPVALUE}":"IP-ADDRESS"
        }
    ]
}

While I would expect it to be:

{
    "data":[
        {
        "{#ADVSNMPINDEX1}": "3",
        "{#ADVSNMPINDEX2}": "0",
        "{#ADVSNMPVALUE}":"IP-ADDRESS"
        }
    ]
}

If the HSRP group is not 0 (eg the full oid is: 1.3.6.1.4.1.9.9.106.1.2.1.1.11.3.100) everything is fine and I get ADVSNMPINDEX1 and ADVSNMPINDEX2.

For your reference this is a snmpwalk:

[root@srvzabbix ~]# snmpwalk IP-ROUTER -v2c -cpublic -On -Ln 1.3.6.1.4.1.9.9.106.1.2.1.1.11
.1.3.6.1.4.1.9.9.106.1.2.1.1.11.3.0 = IpAddress: IP-HSRP

**Comment by cmammoli** [comment]
I suck at perl, but it seems that a variable = 0 is considered empty. I fixed it this way:

```
--- simonkowallik-Zabbix-Addons-37138a8/advsnmp.discovery/advsnmp.discovery 2012-05-04 12:51:28.000000000 +0200
+++ /etc/zabbix/externalscripts/advsnmp.discovery   2012-06-18 13:33:32.510383745 +0200
@@ -165,7 +165,7 @@
     # print all INDEXES
     my $ctr = 1;
     foreach my $index ( split(/;/, $line_index) ) {
-      next if (!$index);
+      next if ($index eq undef);
       print "\t\t\"{#ADVSNMPINDEX$ctr}\": \"$index\",\n";
       $ctr++
     }

```

[root@srvzabbix ~]#  /etc/zabbix/externalscripts/advsnmp.discovery  192.168.3.9 "-v2c -c public" .1.3.6.1.4.1.9.9.106.1.2.1.1.11 1.1 2.1

{
    "data":[
        {
        "{#ADVSNMPINDEX1}": "1",
        "{#ADVSNMPINDEX2}": "0",
        "{#ADVSNMPVALUE}":"10.10.10.5"
        }   ,
        {
        "{#ADVSNMPINDEX1}": "1",
        "{#ADVSNMPINDEX2}": "100",
        "{#ADVSNMPVALUE}":"10.10.10.3"
        }   ,
        {
        "{#ADVSNMPINDEX1}": "1",
        "{#ADVSNMPINDEX2}": "200",
        "{#ADVSNMPVALUE}":"10.10.10.4"
        }
    ]
}

**Comment by simonkowallik** [comment]
Hi cmammoli,
Thanks for reporting the bug and providing the fix.

I updated advsnmp.discovery.

br,
simon
